# Generated by Django 2.2.3 on 2019-08-14 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsrc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youyodauser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
