# Generated by Django 2.2.3 on 2019-09-25 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsrc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursessubscribers',
            name='rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='events',
            name='cover_url',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
