# Generated by Django 2.2.3 on 2019-09-21 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsrc', '0002_pdp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursessubscribers',
            name='rate',
            field=models.IntegerField(default=0),
        ),
    ]
