# Generated by Django 2.2.3 on 2019-08-14 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsrc', '0002_auto_20190814_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='youyodauser',
            name='i_like',
            field=models.TextField(blank=True, null=True),
        ),
    ]
