# Generated by Django 2.2.3 on 2019-09-06 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appsrc', '0002_auto_20190831_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursessubscribers',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribed_course', to='appsrc.Courses'),
        ),
    ]
