# Generated by Django 2.2.3 on 2019-08-15 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsrc', '0002_auto_20190815_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='youyodauser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
