# Generated by Django 2.2.3 on 2019-08-09 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appsrc', '0002_roles_role_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='role_id',
            new_name='role',
        ),
    ]
