# Generated by Django 2.2.3 on 2019-08-14 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appsrc', '0003_auto_20190814_1621'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='youyodauser',
            options={},
        ),
        migrations.AlterModelManagers(
            name='youyodauser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='youyodauser',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='youyodauser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='youyodauser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='youyodauser',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='youyodauser',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='youyodauser',
            name='user_permissions',
        ),
    ]
