# Generated by Django 2.2.3 on 2019-08-14 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsrc', '0003_youyodauser_i_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youyodauser',
            name='is_trainer',
            field=models.BooleanField(default=False),
        ),
    ]
