# Generated by Django 2.2.3 on 2019-08-09 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsrc', '0003_auto_20190809_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Roles',
        ),
    ]
