# Generated by Django 2.2.3 on 2019-08-14 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appsrc', '0004_auto_20190814_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='roles',
            name='role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='youyodauser',
            name='role_id',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
