# Generated by Django 2.2.3 on 2019-08-14 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appsrc', '0004_auto_20190814_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='owner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appsrc.YouYodaUser'),
        ),
        migrations.AlterField(
            model_name='coursessubscribers',
            name='participant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appsrc.YouYodaUser'),
        ),
        migrations.AlterField(
            model_name='events',
            name='owner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appsrc.YouYodaUser'),
        ),
        migrations.AlterField(
            model_name='eventssubscribers',
            name='participant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appsrc.YouYodaUser'),
        ),
        migrations.AlterField(
            model_name='statushistory',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appsrc.YouYodaUser'),
        ),
        migrations.AlterField(
            model_name='trainercertificates',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appsrc.YouYodaUser'),
        ),
    ]
